import marketplaceSdkCatalogJson from './marketplace-sdk-catalog.json';

type SdkLanguageId = 'node' | 'dotnet' | 'java';

interface MarketplaceSdkAction {
  id: string;
  name: string;
  method: string;
  path: string;
  description: string;
}

interface MarketplaceSdkGroup {
  id: string;
  name: string;
  slug: string;
  category: 'email' | 'pdf' | 'automation';
  tagline: string;
  description: string;
  auth: {
    type: 'api_key';
    header: string;
    label: string;
    placeholder: string;
    hint: string;
  };
  features: string[];
  actions: MarketplaceSdkAction[];
}

interface MarketplaceSdkCatalog {
  groups: MarketplaceSdkGroup[];
}

export interface SdkBundle {
  id: SdkLanguageId;
  label: string;
  runtime: string;
  packageLabel: string;
  folderName: string;
  archiveName: string;
  installCommand: string;
  description: string;
  highlights: string[];
  supportedEndpoints: string[];
  preview: string;
  files: Record<string, string>;
}

const DEFAULT_BASE_URL = 'https://api.sendcraft.net';

const MARKETPLACE_SDK_CATALOG = marketplaceSdkCatalogJson as MarketplaceSdkCatalog;
export const MARKETPLACE_SDK_GROUPS = MARKETPLACE_SDK_CATALOG.groups;

const SUPPORTED_ENDPOINTS = MARKETPLACE_SDK_GROUPS.flatMap((group) =>
  group.actions.map((action) => `${action.method} ${action.path}`)
);

function normalizeBaseUrl(value: string): string {
  const trimmed = String(value || '').trim().replace(/\/+$/, '');
  return trimmed || DEFAULT_BASE_URL;
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function literal(value: string): string {
  return JSON.stringify(value);
}

function buildPreviewNode(baseUrl: string): string {
  return [
    'import { SendCraftClient } from "sendcraft-sdk";',
    '',
    'const client = new SendCraftClient({',
    `  baseUrl: ${literal(baseUrl)},`,
    '  apiKey: process.env.SENDCRAFT_API_KEY || "",',
    '});',
    '',
    'const response = await client.sendEmail({',
    '  recipient_email: "cliente@empresa.com",',
    '  template_name: "welcome",',
    '  data: { nombre: "Juan Perez" },',
    '});',
    '',
    'console.log(response);',
  ].join('\n');
}

function buildPreviewDotNet(baseUrl: string): string {
  return [
    'using SendCraft.Sdk;',
    '',
    'var client = new SendCraftClient(',
    `    ${literal(baseUrl)},`,
    '    Environment.GetEnvironmentVariable("SENDCRAFT_API_KEY"));',
    '',
    'var response = await client.SendEmailAsync(new {',
    '    recipient_email = "cliente@empresa.com",',
    '    template_name = "welcome",',
    '    data = new { nombre = "Juan Perez" }',
    '});',
    '',
    'Console.WriteLine(response);',
  ].join('\n');
}

function buildPreviewJava(baseUrl: string): string {
  return [
    'SendCraftClient client = new SendCraftClient(',
    `    ${literal(baseUrl)},`,
    '    System.getenv("SENDCRAFT_API_KEY"));',
    '',
    'Map<String, Object> payload = new HashMap<>();',
    'payload.put("recipient_email", "cliente@empresa.com");',
    'payload.put("template_name", "welcome");',
    'payload.put("data", Map.of("nombre", "Juan Perez"));',
    '',
    'JsonNode response = client.sendEmail(payload);',
    'System.out.println(response.toPrettyString());',
  ].join('\n');
}

function buildNodeStatusScript(_baseUrl: string): string {
  const endpoints = MARKETPLACE_SDK_GROUPS.flatMap((group) =>
    group.actions.map((action) => ({
      group: group.name,
      method: action.method,
      path: action.path,
      pathParams: Array.from(action.path.matchAll(/:([A-Za-z0-9_]+)/g)).map((match) => match[1]),
    }))
  );

  return [
    'import process from "node:process";',
    '',
    'const DEFAULT_BASE_URL = "";',
    `const GROUP_COUNT = ${MARKETPLACE_SDK_GROUPS.length};`,
    `const ENDPOINTS = ${json(endpoints)};`,
    '',
    'function normalizeBaseUrl(value) {',
    '  return String(value || "").trim().replace(/\\/+$/, "");',
    '}',
    '',
    'function resolveBaseUrl() {',
    '  const cliBaseUrlFlag = process.argv.find((arg) => arg.startsWith("--base-url="));',
    '  const cliBaseUrl = cliBaseUrlFlag ? cliBaseUrlFlag.slice("--base-url=".length) : "";',
    '  return normalizeBaseUrl(',
    '    cliBaseUrl ||',
    '    process.env.SDK_BASE_URL ||',
    '    process.env.FUNCTIONS_BASE_URL ||',
    '    process.env.VITE_FUNCTIONS_BASE_URL ||',
    '    DEFAULT_BASE_URL',
    '  );',
    '}',
    '',
    'function sampleValueForParam(paramName) {',
    '  switch (String(paramName || "").toLowerCase()) {',
    '    case "job_id": return "sample-job-id";',
    '    case "programid":',
    '    case "program_id": return "sample-program-id";',
    '    case "queueitemid":',
    '    case "queue_item_id": return "sample-queue-item-id";',
    '    case "log_id": return "sample-log-id";',
    '    default: return `sample-${String(paramName || "value").toLowerCase()}`;',
    '  }',
    '}',
    '',
    'function buildUrl(baseUrl, actionPath) {',
    '  const replacedPath = String(actionPath).replace(/:([A-Za-z0-9_]+)/g, (_, paramName) => sampleValueForParam(paramName));',
    '  return `${baseUrl.replace(/\\/+$/, "")}/${replacedPath.replace(/^\\/+/, "")}`;',
    '}',
    '',
    'function classifyStatus(status) {',
    '  if (status === 404) return { deployed: false, label: "missing" };',
    '  if ([200, 204, 401, 403, 405].includes(status)) return { deployed: true, label: "live" };',
    '  return { deployed: null, label: "check" };',
    '}',
    '',
    'async function main() {',
    '  const baseUrl = resolveBaseUrl();',
    '  console.log("SendCraft public SDK catalog");',
    '  console.log(`Base URL: ${baseUrl || "(not set)"}`);',
    '  console.log(`Groups: ${GROUP_COUNT}`);',
    '  console.log(`Endpoints: ${ENDPOINTS.length}`);',
    '  console.log("");',
    '  console.log("Group | Method | Path | Deployed | Status");',
    '  console.log("--- | --- | --- | --- | ---");',
    '',
    '  if (!baseUrl) {',
    '    for (const endpoint of ENDPOINTS) {',
    '      const pathLabel = endpoint.pathParams.length',
    '        ? `${endpoint.path} (${endpoint.pathParams.join(", ")})`',
    '        : endpoint.path;',
    '      console.log(`${endpoint.group} | ${endpoint.method} | ${pathLabel} | unknown | set SDK_BASE_URL or pass --base-url to probe`);',
    '    }',
    '    return;',
    '  }',
    '',
    '  for (const endpoint of ENDPOINTS) {',
    '    let statusText = "not checked";',
    '    let deployedLabel = "unknown";',
    '    try {',
    '      const response = await fetch(buildUrl(baseUrl, endpoint.path), {',
    '        method: "OPTIONS",',
    '        headers: { Accept: "application/json" },',
    '      });',
    '      const classification = classifyStatus(response.status);',
    '      deployedLabel = classification.deployed === true ? "yes" : classification.deployed === false ? "no" : "maybe";',
    '      statusText = `${classification.label} (${response.status}${response.statusText ? ` ${response.statusText}` : ""})`;',
    '    } catch (error) {',
    '      deployedLabel = "no";',
    '      statusText = error instanceof Error ? error.message : String(error);',
    '    }',
    '',
    '    const pathLabel = endpoint.pathParams.length',
    '      ? `${endpoint.path} (${endpoint.pathParams.join(", ")})`',
    '      : endpoint.path;',
    '    console.log(`${endpoint.group} | ${endpoint.method} | ${pathLabel} | ${deployedLabel} | ${statusText}`);',
    '  }',
    '}',
    '',
    'main().catch((error) => {',
    '  console.error(error);',
    '  process.exitCode = 1;',
    '});',
  ].join('\n');
}

function buildMarketplaceCatalogSections(): string {
  return MARKETPLACE_SDK_GROUPS.map((group) => {
    const actionLines = group.actions
      .map((action) => `- \`${action.method} ${action.path}\` - ${action.description}`)
      .join('\n');
    const featureLines = group.features
      .map((feature) => `- ${feature}`)
      .join('\n');

    return [
      `### ${group.name}`,
      '',
      group.tagline,
      '',
      'Endpoints',
      '',
      actionLines,
      '',
      'Features',
      '',
      featureLines,
    ].join('\n');
  }).join('\n\n');
}

function buildCommonReadme(title: string, baseUrl: string, installCommand: string, usageSnippet: string, extraNotes: string[]) {
  return [
    `# ${title}`,
    '',
    'Starter kit generado desde el Marketplace de SendCraft.',
    '',
    '## Base URL',
    '',
    'La version descargada ya incluye como referencia la URL actual del entorno:',
    '',
    '```',
    baseUrl,
    '```',
    '',
    '## Instalacion local',
    '',
    '1. Descomprime este ZIP en tu maquina o en tu repo.',
    `2. Ejecuta: \`${installCommand}\``,
    '',
    '## Uso rapido',
    '',
    '```',
    usageSnippet,
    '```',
    '',
    '## Catalogo incluido',
    '',
    buildMarketplaceCatalogSections(),
    '',
    '## Notas',
    '',
    ...extraNotes.map((note) => `- ${note}`),
  ].join('\n');
}

function buildNodeFiles(baseUrl: string): Record<string, string> {
  const resolvedBaseUrl = normalizeBaseUrl(baseUrl);

  return {
    'package.json': json({
      name: 'sendcraft-sdk',
      version: '1.0.0',
      description: 'SendCraft API client generated from the Marketplace catalog.',
      type: 'module',
      main: './index.js',
      types: './index.d.ts',
      exports: {
        '.': {
          types: './index.d.ts',
          default: './index.js',
        },
      },
      scripts: {
        'sdk:status': 'node ./scripts/sdk-status.mjs',
      },
      engines: {
        node: '>=18',
      },
      license: 'MIT',
    }),
    'index.js': [
      `const DEFAULT_BASE_URL = ${literal(resolvedBaseUrl)};`,
      '',
      'function normalizeBaseUrl(value) {',
      '  return String(value || DEFAULT_BASE_URL).trim().replace(/\\/+$/, "");',
      '}',
      '',
      'function buildUrl(baseUrl, path) {',
      '  return normalizeBaseUrl(baseUrl) + "/" + String(path).replace(/^\\/+/, "");',
      '}',
      '',
      'function appendQueryParams(url, query) {',
      '  const resolved = new URL(url);',
      '  Object.entries(query || {}).forEach(([key, value]) => {',
      '    if (value === undefined || value === null || value === "") return;',
      '    resolved.searchParams.set(key, String(value));',
      '  });',
      '  return resolved.toString();',
      '}',
      '',
      'function extractMessage(payload, status) {',
      '  if (payload && typeof payload === "object") {',
      '    if (typeof payload.error === "string") return payload.error;',
      '    if (payload.error && typeof payload.error === "object" && typeof payload.error.message === "string") return payload.error.message;',
      '    if (typeof payload.message === "string") return payload.message;',
      '  }',
      '  return "Request failed (" + status + ")";',
      '}',
      '',
      'export class SendCraftError extends Error {',
      '  constructor(message, status, details) {',
      '    super(message);',
      '    this.name = "SendCraftError";',
      '    this.status = status;',
      '    this.details = details;',
      '  }',
      '}',
      '',
      'export class SendCraftClient {',
      '  constructor(options = {}) {',
      '    const { baseUrl = DEFAULT_BASE_URL, apiKey = "", fetchImpl = globalThis.fetch?.bind(globalThis) } = options;',
      '    if (!fetchImpl) {',
      '      throw new Error("fetch is not available in this runtime");',
      '    }',
      '    this.baseUrl = normalizeBaseUrl(baseUrl);',
      '    this.apiKey = String(apiKey || "").trim();',
      '    this.fetchImpl = fetchImpl;',
      '  }',
      '',
      '  async request(path, options = {}) {',
      '    const url = appendQueryParams(buildUrl(this.baseUrl, path), options.query);',
      '    const headers = { ...(options.headers || {}) };',
      '    if (options.body !== undefined && options.body !== null) {',
      '      headers["Content-Type"] = "application/json";',
      '    }',
      '    if (this.apiKey) {',
      '      headers["x-api-key"] = this.apiKey;',
      '    }',
      '',
      '    const response = await this.fetchImpl(url, {',
      '      method: options.method || "GET",',
      '      headers,',
      '      body: options.body !== undefined && options.body !== null ? JSON.stringify(options.body) : undefined,',
      '    });',
      '',
      '    const text = await response.text();',
      '    let payload = null;',
      '    if (text) {',
      '      try {',
      '        payload = JSON.parse(text);',
      '      } catch {',
      '        payload = text;',
      '      }',
      '    }',
      '',
      '    if (!response.ok || (payload && typeof payload === "object" && payload.success === false)) {',
      '      throw new SendCraftError(extractMessage(payload, response.status), response.status, payload);',
      '    }',
      '',
      '    return payload;',
      '  }',
      '',
      '  sendEmail(payload) {',
      '    return this.request("/send-email", { method: "POST", body: payload });',
      '  }',
      '',
      '  sendEmailWithPdf(payload) {',
      '    return this.request("/send-email-with-pdf", { method: "POST", body: payload });',
      '  }',
      '',
      '  generatePdf(payload) {',
      '    return this.request("/generate-pdf", { method: "POST", body: payload });',
      '  }',
      '',
      '  notify(payload) {',
      '    return this.request("/notify", { method: "POST", body: payload });',
      '  }',
      '',
      '  notifyStatus(jobId) {',
      '    return this.request("/notify/" + encodeURIComponent(String(jobId)), { method: "GET" });',
      '  }',
      '',
      '  listPrograms(query = {}) {',
      '    return this.request("/automation-programs", { method: "GET", query });',
      '  }',
      '',
      '  createProgram(payload) {',
      '    return this.request("/automation-programs", { method: "POST", body: payload });',
      '  }',
      '',
      '  updateProgram(programId, payload) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)), { method: "PUT", body: payload });',
      '  }',
      '',
      '  deleteProgram(programId) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)), { method: "DELETE" });',
      '  }',
      '',
      '  runProgram(programId) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)) + "/run", { method: "POST" });',
      '  }',
      '',
      '  loadProgramQueue(programId, query = {}) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)) + "/queue", { method: "GET", query });',
      '  }',
      '',
      '  enqueueProgramQueue(programId, payload) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)) + "/queue", { method: "POST", body: payload });',
      '  }',
      '',
      '  cancelProgramQueueItem(programId, queueItemId) {',
      '    return this.request("/automation-programs/" + encodeURIComponent(String(programId)) + "/queue/" + encodeURIComponent(String(queueItemId)), { method: "DELETE" });',
      '  }',
      '',
      '  loadMonitoring(query = {}) {',
      '    return this.request("/automation-monitoring", { method: "GET", query });',
      '  }',
      '}',
      '',
      'export default SendCraftClient;',
    ].join('\n'),
    'index.d.ts': [
      'export type QueryValue = string | number | boolean | null | undefined;',
      'export type QueryMap = Record<string, QueryValue>;',
      'export type RecordMap = Record<string, unknown>;',
      '',
      'export interface SendCraftClientOptions {',
      '  baseUrl?: string;',
      '  apiKey?: string;',
      '  fetchImpl?: typeof fetch;',
      '}',
      '',
      'export interface SendEmailPayload {',
      '  recipient_email: string;',
      '  template_name: string;',
      '  data?: RecordMap;',
      '  subject?: string;',
      '  order_id?: string;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface SendEmailWithPdfPayload {',
      '  recipient_email: string;',
      '  email: {',
      '    template_name: string;',
      '    subject?: string;',
      '    data?: RecordMap;',
      '    [key: string]: unknown;',
      '  };',
      '  attachment: {',
      '    pdf_template_name: string;',
      '    filename?: string;',
      '    data?: RecordMap;',
      '    [key: string]: unknown;',
      '  };',
      '  order_id?: string;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface GeneratePdfPayload {',
      '  template_id?: string;',
      '  pdf_template_name?: string;',
      '  data: RecordMap;',
      '  order_id?: string;',
      '  pending_communication_id?: string;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface AutomationBatchPayload {',
      '  type: "email" | "email_pdf" | "pdf";',
      '  template_name?: string;',
      '  attachment?: {',
      '    pdf_template_name: string;',
      '    filename?: string;',
      '    data?: RecordMap;',
      '    [key: string]: unknown;',
      '  };',
      '  recipients: Array<{ email: string; data?: RecordMap }>;',
      '  shared_data?: RecordMap;',
      '  options?: RecordMap;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface AutomationProgramInput {',
      '  id?: string;',
      '  name: string;',
      '  kind: "scheduled" | "batch";',
      '  status?: "draft" | "scheduled" | "active" | "paused" | "done" | "failed" | "cancelled";',
      '  delivery_mode?: "static" | "queued";',
      '  channel: "email" | "email_pdf" | "pdf";',
      '  template_name?: string | null;',
      '  pdf_template_name?: string | null;',
      '  pdf_filename_pattern?: string | null;',
      '  recipients?: Array<{ email: string; data?: RecordMap }>;',
      '  shared_data?: RecordMap;',
      '  options?: RecordMap;',
      '  schedule_at?: string | null;',
      '  cron_expression?: string | null;',
      '  timezone?: string | null;',
      '  metadata?: RecordMap;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface AutomationProgramQueueInput {',
      '  external_reference_id?: string | null;',
      '  recipient_email?: string;',
      '  recipient_data?: RecordMap;',
      '  shared_data?: RecordMap;',
      '  options?: RecordMap;',
      '  available_at?: string | null;',
      '  metadata?: RecordMap;',
      '  [key: string]: unknown;',
      '}',
      '',
      'export interface ProgramQuery {',
      '  kind?: string;',
      '  status?: string;',
      '  due?: boolean;',
      '  limit?: number;',
      '}',
      '',
      'export interface QueueQuery {',
      '  status?: string;',
      '  limit?: number;',
      '}',
      '',
      'export interface MonitoringQuery {',
      '  limit?: number;',
      '}',
      '',
      'export declare class SendCraftError extends Error {',
      '  status: number;',
      '  details: unknown;',
      '  constructor(message: string, status: number, details?: unknown);',
      '}',
      '',
      'export declare class SendCraftClient {',
      '  constructor(options?: SendCraftClientOptions);',
      '  request(path: string, options?: { method?: string; headers?: Record<string, string>; body?: unknown; query?: QueryMap }): Promise<unknown>;',
      '  sendEmail(payload: SendEmailPayload): Promise<unknown>;',
      '  sendEmailWithPdf(payload: SendEmailWithPdfPayload): Promise<unknown>;',
      '  generatePdf(payload: GeneratePdfPayload): Promise<unknown>;',
      '  notify(payload: AutomationBatchPayload): Promise<unknown>;',
      '  notifyStatus(jobId: string): Promise<unknown>;',
      '  listPrograms(query?: ProgramQuery): Promise<unknown>;',
      '  createProgram(payload: AutomationProgramInput): Promise<unknown>;',
      '  updateProgram(programId: string, payload: AutomationProgramInput): Promise<unknown>;',
      '  deleteProgram(programId: string): Promise<unknown>;',
      '  runProgram(programId: string): Promise<unknown>;',
      '  loadProgramQueue(programId: string, query?: QueueQuery): Promise<unknown>;',
      '  enqueueProgramQueue(programId: string, payload: AutomationProgramQueueInput | Array<AutomationProgramQueueInput>): Promise<unknown>;',
      '  cancelProgramQueueItem(programId: string, queueItemId: string): Promise<unknown>;',
      '  loadMonitoring(query?: MonitoringQuery): Promise<unknown>;',
      '}',
      '',
      'export default SendCraftClient;',
    ].join('\n'),
    'README.md': buildCommonReadme(
      'SendCraft Node.js SDK',
      resolvedBaseUrl,
      'npm install file:./sendcraft-node-sdk',
      buildPreviewNode(resolvedBaseUrl),
      [
      'Pensado para Node 18+ con `fetch` nativo.',
      'Incluye helpers para email, PDF, automatizaciones y monitoreo.',
      'Se puede usar como paquete local o publicarlo en npm luego de ajustarlo.',
        'Incluye `npm run sdk:status` para listar los endpoints y `--base-url` para probar un despliegue.',
      ],
    ),
    'scripts/sdk-status.mjs': buildNodeStatusScript(resolvedBaseUrl),
  };
}

function buildDotNetFiles(baseUrl: string): Record<string, string> {
  const resolvedBaseUrl = normalizeBaseUrl(baseUrl);

  return {
    'SendCraft.Sdk.csproj': [
      '<Project Sdk="Microsoft.NET.Sdk">',
      '  <PropertyGroup>',
      '    <TargetFramework>net8.0</TargetFramework>',
      '    <ImplicitUsings>enable</ImplicitUsings>',
      '    <Nullable>enable</Nullable>',
      '    <PackageId>SendCraft.Sdk</PackageId>',
      '    <Version>1.0.0</Version>',
      '    <Authors>SendCraft</Authors>',
      '    <Description>SendCraft API client generated from the Marketplace catalog.</Description>',
      '  </PropertyGroup>',
      '</Project>',
    ].join('\n'),
    'SendCraftClient.cs': [
      'using System.Net.Http;',
      'using System.Text;',
      'using System.Text.Json;',
      'using System.Text.Json.Nodes;',
      '',
      'namespace SendCraft.Sdk;',
      '',
      'public sealed class SendCraftClient',
      '{',
      '    private static readonly JsonSerializerOptions JsonOptions = new()',
      '    {',
      '        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,',
      '        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull',
      '    };',
      '',
      '    private readonly HttpClient _httpClient;',
      '    private readonly string _baseUrl;',
      '    private readonly string _apiKey;',
      '',
      '    public SendCraftClient(string baseUrl, string? apiKey = null, HttpClient? httpClient = null)',
      '    {',
      `        _baseUrl = NormalizeBaseUrl(string.IsNullOrWhiteSpace(baseUrl) ? ${literal(resolvedBaseUrl)} : baseUrl);`,
      '        _apiKey = (apiKey ?? string.Empty).Trim();',
      '        _httpClient = httpClient ?? new HttpClient();',
      '    }',
      '',
      '    public Task<JsonNode?> SendEmailAsync(object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/send-email", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> SendEmailWithPdfAsync(object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/send-email-with-pdf", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> GeneratePdfAsync(object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/generate-pdf", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> NotifyAsync(object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/notify", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> NotifyStatusAsync(string jobId, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Get, "/notify/" + Uri.EscapeDataString(jobId), null, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> ListProgramsAsync(Dictionary<string, object?>? query = null, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Get, "/automation-programs", null, query, cancellationToken);',
      '',
      '    public Task<JsonNode?> CreateProgramAsync(object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/automation-programs", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> UpdateProgramAsync(string programId, object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Put, "/automation-programs/" + Uri.EscapeDataString(programId), request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> DeleteProgramAsync(string programId, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Delete, "/automation-programs/" + Uri.EscapeDataString(programId), null, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> RunProgramAsync(string programId, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/automation-programs/" + Uri.EscapeDataString(programId) + "/run", null, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> LoadProgramQueueAsync(string programId, Dictionary<string, object?>? query = null, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Get, "/automation-programs/" + Uri.EscapeDataString(programId) + "/queue", null, query, cancellationToken);',
      '',
      '    public Task<JsonNode?> EnqueueProgramQueueAsync(string programId, object request, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Post, "/automation-programs/" + Uri.EscapeDataString(programId) + "/queue", request, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> CancelProgramQueueItemAsync(string programId, string queueItemId, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Delete, "/automation-programs/" + Uri.EscapeDataString(programId) + "/queue/" + Uri.EscapeDataString(queueItemId), null, null, cancellationToken);',
      '',
      '    public Task<JsonNode?> LoadMonitoringAsync(Dictionary<string, object?>? query = null, CancellationToken cancellationToken = default) =>',
      '        SendAsync(HttpMethod.Get, "/automation-monitoring", null, query, cancellationToken);',
      '',
      '    private async Task<JsonNode?> SendAsync(HttpMethod method, string path, object? body, Dictionary<string, object?>? query, CancellationToken cancellationToken)',
      '    {',
      '        var requestUri = BuildUri(path, query);',
      '        using var request = new HttpRequestMessage(method, requestUri);',
      '',
      '        if (!string.IsNullOrWhiteSpace(_apiKey))',
      '        {',
      '            request.Headers.TryAddWithoutValidation("x-api-key", _apiKey);',
      '        }',
      '',
      '        if (body is not null)',
      '        {',
      '            request.Content = new StringContent(JsonSerializer.Serialize(body, JsonOptions), Encoding.UTF8, "application/json");',
      '        }',
      '',
      '        using var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);',
      '        var raw = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);',
      '        JsonNode? payload = string.IsNullOrWhiteSpace(raw) ? null : JsonNode.Parse(raw);',
      '',
      '        if (!response.IsSuccessStatusCode || IsFailurePayload(payload))',
      '        {',
      '            throw new SendCraftException(BuildErrorMessage(payload, (int)response.StatusCode), (int)response.StatusCode, payload);',
      '        }',
      '',
      '        return payload;',
      '    }',
      '',
      '    private string BuildUri(string path, Dictionary<string, object?>? query)',
      '    {',
      '        var uri = CombineUrl(_baseUrl, path);',
      '        if (query is null || query.Count == 0)',
      '        {',
      '            return uri;',
      '        }',
      '',
      '        var pairs = query',
      '            .Where(item => item.Value is not null && item.Value?.ToString() != string.Empty)',
      '            .Select(item => Uri.EscapeDataString(item.Key) + "=" + Uri.EscapeDataString(item.Value!.ToString()!));',
      '',
      '        var queryString = string.Join("&", pairs);',
      '        if (string.IsNullOrWhiteSpace(queryString))',
      '        {',
      '            return uri;',
      '        }',
      '',
      '        return uri + (uri.Contains("?") ? "&" : "?") + queryString;',
      '    }',
      '',
      '    private static string CombineUrl(string baseUrl, string path)',
      '    {',
      '        return baseUrl.TrimEnd(\'/\') + "/" + path.TrimStart(\'/\');',
      '    }',
      '',
      '    private static string NormalizeBaseUrl(string value)',
      '    {',
      '        var trimmed = (value ?? string.Empty).Trim().TrimEnd(\'/\');',
      '        return string.IsNullOrWhiteSpace(trimmed) ? ' + literal(resolvedBaseUrl) + ' : trimmed;',
      '    }',
      '',
      '    private static bool IsFailurePayload(JsonNode? payload)',
      '    {',
      '        if (payload is null)',
      '        {',
      '            return false;',
      '        }',
      '',
      '        var successNode = payload["success"];',
      '        if (successNode is JsonValue successValue && successValue.TryGetValue<bool>(out var success) && !success)',
      '        {',
      '            return true;',
      '        }',
      '',
      '        return payload["error"] is not null;',
      '    }',
      '',
      '    private static string BuildErrorMessage(JsonNode? payload, int statusCode)',
      '    {',
      '        if (payload is not null)',
      '        {',
      '            var error = payload["error"];',
      '            if (error is JsonValue value && value.TryGetValue<string>(out var errorText) && !string.IsNullOrWhiteSpace(errorText))',
      '            {',
      '                return errorText;',
      '            }',
      '',
      '            var message = payload["message"]?.ToString();',
      '            if (!string.IsNullOrWhiteSpace(message))',
      '            {',
      '                return message;',
      '            }',
      '        }',
      '',
      '        return "Request failed (" + statusCode + ")";',
      '    }',
      '}',
    ].join('\n'),
    'SendCraftException.cs': [
      'using System.Text.Json.Nodes;',
      '',
      'namespace SendCraft.Sdk;',
      '',
      'public sealed class SendCraftException : Exception',
      '{',
      '    public int StatusCode { get; }',
      '    public JsonNode? Payload { get; }',
      '',
      '    public SendCraftException(string message, int statusCode, JsonNode? payload = null)',
      '        : base(message)',
      '    {',
      '        StatusCode = statusCode;',
      '        Payload = payload;',
      '    }',
      '}',
    ].join('\n'),
    'README.md': buildCommonReadme(
      'SendCraft .NET SDK',
      resolvedBaseUrl,
      'dotnet add reference ./SendCraft.Sdk.csproj',
      buildPreviewDotNet(resolvedBaseUrl),
      [
        'Pensado para .NET 8 con `System.Text.Json`.',
        'Devuelve `JsonNode` para que puedas mapear la respuesta a tu dominio.',
        'Si lo preferis, luego lo podes publicar como paquete NuGet.',
      ],
    ),
  };
}

function buildJavaFiles(baseUrl: string): Record<string, string> {
  const resolvedBaseUrl = normalizeBaseUrl(baseUrl);

  return {
    'pom.xml': [
      '<project xmlns="http://maven.apache.org/POM/4.0.0"',
      '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
      '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">',
      '  <modelVersion>4.0.0</modelVersion>',
      '  <groupId>com.sendcraft</groupId>',
      '  <artifactId>sendcraft-sdk</artifactId>',
      '  <version>1.0.0</version>',
      '  <name>SendCraft SDK</name>',
      '  <description>SendCraft API client generated from the Marketplace catalog.</description>',
      '  <properties>',
      '    <maven.compiler.source>17</maven.compiler.source>',
      '    <maven.compiler.target>17</maven.compiler.target>',
      '    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>',
      '    <jackson.version>2.17.2</jackson.version>',
      '  </properties>',
      '  <dependencies>',
      '    <dependency>',
      '      <groupId>com.fasterxml.jackson.core</groupId>',
      '      <artifactId>jackson-databind</artifactId>',
      '      <version>${jackson.version}</version>',
      '    </dependency>',
      '  </dependencies>',
      '</project>',
    ].join('\n'),
    'src/main/java/com/sendcraft/sdk/SendCraftClient.java': [
      'package com.sendcraft.sdk;',
      '',
      'import com.fasterxml.jackson.core.JsonProcessingException;',
      'import com.fasterxml.jackson.databind.JsonNode;',
      'import com.fasterxml.jackson.databind.ObjectMapper;',
      '',
      'import java.io.IOException;',
      'import java.net.URI;',
      'import java.net.URLEncoder;',
      'import java.net.http.HttpClient;',
      'import java.net.http.HttpRequest;',
      'import java.net.http.HttpResponse;',
      'import java.nio.charset.StandardCharsets;',
      'import java.util.ArrayList;',
      'import java.util.HashMap;',
      'import java.util.List;',
      'import java.util.Map;',
      '',
      'public class SendCraftClient {',
      '    private static final String DEFAULT_BASE_URL = ' + literal(resolvedBaseUrl) + ';',
      '',
      '    private final HttpClient httpClient;',
      '    private final ObjectMapper objectMapper;',
      '    private final String baseUrl;',
      '    private final String apiKey;',
      '',
      '    public SendCraftClient(String baseUrl) {',
      '        this(baseUrl, null, null);',
      '    }',
      '',
      '    public SendCraftClient(String baseUrl, String apiKey) {',
      '        this(baseUrl, apiKey, null);',
      '    }',
      '',
      '    public SendCraftClient(String baseUrl, String apiKey, HttpClient httpClient) {',
      '        this.baseUrl = normalizeBaseUrl(baseUrl);',
      '        this.apiKey = apiKey == null ? "" : apiKey.trim();',
      '        this.httpClient = httpClient == null ? HttpClient.newHttpClient() : httpClient;',
      '        this.objectMapper = new ObjectMapper();',
      '    }',
      '',
      '    public JsonNode sendEmail(Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/send-email", payload, null);',
      '    }',
      '',
      '    public JsonNode sendEmailWithPdf(Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/send-email-with-pdf", payload, null);',
      '    }',
      '',
      '    public JsonNode generatePdf(Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/generate-pdf", payload, null);',
      '    }',
      '',
      '    public JsonNode notify(Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/notify", payload, null);',
      '    }',
      '',
      '    public JsonNode notifyStatus(String jobId) throws IOException, InterruptedException {',
      '        return request("GET", "/notify/" + encode(jobId), null, null);',
      '    }',
      '',
      '    public JsonNode listPrograms(Map<String, Object> query) throws IOException, InterruptedException {',
      '        return request("GET", "/automation-programs", null, query);',
      '    }',
      '',
      '    public JsonNode createProgram(Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/automation-programs", payload, null);',
      '    }',
      '',
      '    public JsonNode updateProgram(String programId, Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("PUT", "/automation-programs/" + encode(programId), payload, null);',
      '    }',
      '',
      '    public JsonNode deleteProgram(String programId) throws IOException, InterruptedException {',
      '        return request("DELETE", "/automation-programs/" + encode(programId), null, null);',
      '    }',
      '',
      '    public JsonNode runProgram(String programId) throws IOException, InterruptedException {',
      '        return request("POST", "/automation-programs/" + encode(programId) + "/run", null, null);',
      '    }',
      '',
      '    public JsonNode loadProgramQueue(String programId, Map<String, Object> query) throws IOException, InterruptedException {',
      '        return request("GET", "/automation-programs/" + encode(programId) + "/queue", null, query);',
      '    }',
      '',
      '    public JsonNode enqueueProgramQueue(String programId, Map<String, Object> payload) throws IOException, InterruptedException {',
      '        return request("POST", "/automation-programs/" + encode(programId) + "/queue", payload, null);',
      '    }',
      '',
      '    public JsonNode cancelProgramQueueItem(String programId, String queueItemId) throws IOException, InterruptedException {',
      '        return request("DELETE", "/automation-programs/" + encode(programId) + "/queue/" + encode(queueItemId), null, null);',
      '    }',
      '',
      '    public JsonNode loadMonitoring(Map<String, Object> query) throws IOException, InterruptedException {',
      '        return request("GET", "/automation-monitoring", null, query);',
      '    }',
      '',
      '    private JsonNode request(String method, String path, Map<String, Object> body, Map<String, Object> query) throws IOException, InterruptedException {',
      '        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(buildUri(path, query))).method(method, body == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(objectMapper.writeValueAsString(body), StandardCharsets.UTF_8));',
      '        builder.header("Accept", "application/json");',
      '        if (body != null) {',
      '            builder.header("Content-Type", "application/json");',
      '        }',
      '        if (!apiKey.isBlank()) {',
      '            builder.header("x-api-key", apiKey);',
      '        }',
      '',
      '        HttpResponse<String> response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));',
      '        JsonNode payload = response.body() == null || response.body().isBlank() ? null : objectMapper.readTree(response.body());',
      '        if (response.statusCode() >= 400 || isFailurePayload(payload)) {',
      '            throw new SendCraftException(buildErrorMessage(payload, response.statusCode()), response.statusCode(), payload);',
      '        }',
      '        return payload;',
      '    }',
      '',
      '    private String buildUri(String path, Map<String, Object> query) {',
      '        String uri = combine(baseUrl, path);',
      '        if (query == null || query.isEmpty()) {',
      '            return uri;',
      '        }',
      '        List<String> params = new ArrayList<>();',
      '        for (Map.Entry<String, Object> entry : query.entrySet()) {',
      '            if (entry.getValue() == null) {',
      '                continue;',
      '            }',
      '            String text = entry.getValue().toString();',
      '            if (text.isBlank()) {',
      '                continue;',
      '            }',
      '            params.add(encode(entry.getKey()) + "=" + encode(text));',
      '        }',
      '        if (params.isEmpty()) {',
      '            return uri;',
      '        }',
      '        return uri + "?" + String.join("&", params);',
      '    }',
      '',
      '    private static String combine(String base, String path) {',
      '        return base.replaceAll("/+$", "") + "/" + path.replaceAll("^/+", "");',
      '    }',
      '',
      '    private static String normalizeBaseUrl(String value) {',
      '        if (value == null || value.isBlank()) {',
      '            return DEFAULT_BASE_URL;',
      '        }',
      '        return value.trim().replaceAll("/+$", "");',
      '    }',
      '',
      '    private static String encode(String value) {',
      '        return URLEncoder.encode(value, StandardCharsets.UTF_8);',
      '    }',
      '',
      '    private static boolean isFailurePayload(JsonNode payload) {',
      '        if (payload == null) {',
      '            return false;',
      '        }',
      '        JsonNode success = payload.get("success");',
      '        if (success != null && success.isBoolean() && !success.booleanValue()) {',
      '            return true;',
      '        }',
      '        return payload.hasNonNull("error");',
      '    }',
      '',
      '    private static String buildErrorMessage(JsonNode payload, int statusCode) {',
      '        if (payload != null) {',
      '            JsonNode error = payload.get("error");',
      '            if (error != null && error.isTextual()) {',
      '                return error.asText();',
      '            }',
      '            JsonNode message = payload.get("message");',
      '            if (message != null && message.isTextual()) {',
      '                return message.asText();',
      '            }',
      '        }',
      '        return "Request failed (" + statusCode + ")";',
      '    }',
      '}',
    ].join('\n'),
    'src/main/java/com/sendcraft/sdk/SendCraftException.java': [
      'package com.sendcraft.sdk;',
      '',
      'import com.fasterxml.jackson.databind.JsonNode;',
      '',
      'public class SendCraftException extends RuntimeException {',
      '    private final int statusCode;',
      '    private final JsonNode payload;',
      '',
      '    public SendCraftException(String message, int statusCode, JsonNode payload) {',
      '        super(message);',
      '        this.statusCode = statusCode;',
      '        this.payload = payload;',
      '    }',
      '',
      '    public int getStatusCode() {',
      '        return statusCode;',
      '    }',
      '',
      '    public JsonNode getPayload() {',
      '        return payload;',
      '    }',
      '}',
    ].join('\n'),
    'README.md': buildCommonReadme(
      'SendCraft Java SDK',
      resolvedBaseUrl,
      'mvn install',
      buildPreviewJava(resolvedBaseUrl),
      [
        'Pensado para Java 17+ con Maven y Jackson.',
        'Instalalo en el repositorio local con `mvn install` y luego consumilo como dependencia.',
        'Si preferis Gradle, el codigo tambien se puede adaptar facilmente.',
      ],
    ),
  };
}

const SDK_BUILDERS: Record<SdkLanguageId, (baseUrl: string) => SdkBundle> = {
  node: (baseUrl) => ({
    id: 'node',
    label: 'Node.js',
    runtime: 'Node 18+',
    packageLabel: 'npm',
    folderName: 'sendcraft-node-sdk',
    archiveName: 'sendcraft-node-sdk.zip',
    installCommand: 'npm install file:./sendcraft-node-sdk',
    description: 'Cliente fetch-based listo para backend Node.js y apps server-side.',
    highlights: [
      'Headers con x-api-key',
      'Helpers para email, PDF y automatizaciones',
      'Manejo de errores tipado',
    ],
    supportedEndpoints: SUPPORTED_ENDPOINTS,
    preview: buildPreviewNode(baseUrl),
    files: buildNodeFiles(baseUrl),
  }),
  dotnet: (baseUrl) => ({
    id: 'dotnet',
    label: '.NET',
    runtime: '.NET 8+',
    packageLabel: 'NuGet',
    folderName: 'SendCraft.Sdk',
    archiveName: 'sendcraft-dotnet-sdk.zip',
    installCommand: 'dotnet add reference ./SendCraft.Sdk.csproj',
    description: 'SDK para servicios, APIs y workers .NET con HttpClient y JsonNode.',
    highlights: [
      'HttpClient inyectable',
      'Respuestas como JsonNode',
      'Base URL configurable por entorno',
    ],
    supportedEndpoints: SUPPORTED_ENDPOINTS,
    preview: buildPreviewDotNet(baseUrl),
    files: buildDotNetFiles(baseUrl),
  }),
  java: (baseUrl) => ({
    id: 'java',
    label: 'Java',
    runtime: 'Java 17+',
    packageLabel: 'Maven',
    folderName: 'sendcraft-java-sdk',
    archiveName: 'sendcraft-java-sdk.zip',
    installCommand: 'mvn install',
    description: 'Cliente Java con HttpClient y Jackson para integraciones de backend.',
    highlights: [
      'Compatible con Maven',
      'Errores tipados por status',
      'Helpers para query params',
    ],
    supportedEndpoints: SUPPORTED_ENDPOINTS,
    preview: buildPreviewJava(baseUrl),
    files: buildJavaFiles(baseUrl),
  }),
};

export function buildSdkBundle(language: SdkLanguageId, baseUrl: string): SdkBundle {
  return SDK_BUILDERS[language](normalizeBaseUrl(baseUrl));
}

export const SDK_LANGUAGES: Array<{ id: SdkLanguageId; label: string }> = [
  { id: 'node', label: 'Node.js' },
  { id: 'dotnet', label: '.NET' },
  { id: 'java', label: 'Java' },
];

export const SDK_SUPPORT_SUMMARY = SUPPORTED_ENDPOINTS;
